#!/usr/bin/python

from urllib import urlopen
from json import loads
from irenicurse.widget import FullListWidget, bind_to_key
from irenicurse import run

class Generic(FullListWidget):
    "tempory widget to explore api"
    def __init__(self, url):
        self.url = url
        self.content = map(unicode, loads(urlopen(self.url).read()))
        FullListWidget.__init__(self, self.content)

class Home(FullListWidget):
    def __init__(self, url="http://localhost:8080"):
        self.url = url
        self.dictionary = loads(urlopen(self.url).read())
        self.content = sorted(self.dictionary.keys())
        FullListWidget.__init__(self, self.content)

    def get_title(self):
        return "Hargrimm 0.0.git - Home"

    @bind_to_key("enter")
    def enter_section(self):
        self.call(Generic(self.url + self.dictionary[self.get_current_item()]))

if __name__ == "__main__":
    run(Home())
